/*************************************************
 * SukraasLIS
 * @exports
 * Constants.js
 * Created by Jagadish Sellamuthu on 12/05/2020
 * Copyright © 2020 SukraasLIS. All rights reserved.
 *************************************************/

'use strict';

/**
 * Returns all the constants used in the application
 * Separate constants according to the category and usage
 */
module.exports = {
  SCREEN_SIZE: {
    PLUS_SIZE: 667,
  },
  ACTIONS: {
    //Common Actions
    NETWORK_STATUS_CHANGED: 'NETWORK_STATUS_CHANGED',
    APP_GOES_TO_BACKGROUND: 'APP_GOES_TO_BACKGROUND',

    //Splash Screen Actions
    UPDATE_ONE_SIGNAL_DETAILS: 'UPDATE_ONE_SIGNAL_DETAILS',
    SPLASH_SHOW_LOADING: 'SPLASH_SHOW_LOADING',
    SPLASH_HIDE_LOADING: 'SPLASH_HIDE_LOADING',
    SPLASH_ERROR_UPDATE: 'SPLASH_ERROR_UPDATE',

    //Register Screen Action
    REGISTER_SHOW_LOADING: 'REGISTER_SHOW_LOADING',
    REGISTER_HIDE_LOADING: 'REGISTER_HIDE_LOADING',

    //Login Screen Actions
    LOGIN_SHOW_PAGE_LOADING: 'LOGIN_SHOW_PAGE_LOADING',
    LOGIN_HIDE_PAGE_LOADING: 'LOGIN_HIDE_PAGE_LOADING',
    LOGIN_SHOW_LOADING: 'LOGIN_SHOW_LOADING',
    LOGIN_HIDE_LOADING: 'LOGIN_HIDE_LOADING',
    FORGET_PWD_SHOW_LOADING: 'FORGET_PWD_SHOW_LOADING',
    FORGET_PWD_HIDE_LOADING: 'FORGET_PWD_HIDE_LOADING',

    //Signup Screen Actions
    SIGNUP_SHOW_PAGE_LOADING: 'SIGNUP_SHOW_PAGE_LOADING',
    SIGNUP_HIDE_PAGE_LOADING: 'SIGNUP_HIDE_PAGE_LOADING',
    SIGNUP_SHOW_LOADING: 'SIGNUP_SHOW_LOADING',
    SIGNUP_HIDE_LOADING: 'SIGNUP_HIDE_LOADING',
    SIGNUP_SET_CHECKING_STATUS: 'SIGNUP_SET_CHECKING_STATUS',
    SIGNUP_SET_DOB_NEED_OR_NOT: 'SIGNUP_SET_DOB_NEED_OR_NOT',
    SIGNUP_SET_USERNAME_VALID_OR_NOT: 'SIGNUP_SET_USERNAME_VALID_OR_NOT',
    SIGNUP_RESET_TO_INITIAL: 'SIGNUP_RESET_TO_INITIAL',

    //Verify OTP Screen Actions
    OTP_VERIFY_SHOW_LOADING: 'OTP_VERIFY_SHOW_LOADING',
    OTP_VERIFY_HIDE_LOADING: 'OTP_VERIFY_HIDE_LOADING',
    OTP_RESEND_SHOW_LOADING: 'OTP_RESEND_SHOW_LOADING',
    OTP_RESEND_HIDE_LOADING: 'OTP_RESEND_HIDE_LOADING',

    //Submit Password
    SET_PASSWORD_SHOW_LOADING: 'SET_PASSWORD_SHOW_LOADING',
    SET_PASSWORD_HIDE_LOADING: 'SET_PASSWORD_HIDE_LOADING',

    // Booking orderList Action
    BOOKING_SHOW_LOADING: 'BOOKING_SHOW_LOADING',
    BOOKING_HIDE_LOADING: 'BOOKING_HIDE_LOADING',
    SHOW_PULL_TO_REFRESH_LOADING: 'SHOW_PULL_TO_REFRESH_LOADING',
    HIDE_PULL_TO_REFRESH_LOADING: 'HIDE_PULL_TO_REFRESH_LOADING',
    GET_BOOKING_ORDER_LIST: 'GET_BOOKING_ORDER_LIST',

    // Offer screen related
    SHOW_OFFER_SCREEN_LOADING: 'SHOW_OFFER_SCREEN_LOADING',
    HIDE_OFFER_SCREEN_LOADING: 'HIDE_OFFER_SCREEN_LOADING',
    SHOW_OFFER_SCREEN_TEST_LOADING: 'SHOW_OFFER_SCREEN_TEST_LOADING',
    HIDE_OFFER_SCREEN_TEST_LOADING: 'HIDE_OFFER_SCREEN_TEST_LOADING',
    GET_OFFER_DETAILS_SUCCESS: 'GET_OFFER_DETAILS_SUCCESS',
    BOOK_NOW_OFFERS_CART: 'BOOK_NOW_OFFERS_CART',
    BOOK_NOW_CART_COUNT: 'BOOK_NOW_CART_COUNT',
    BOOK_NOW_CART_AMOUNT: 'BOOK_NOW_CART_AMOUNT',

    // Promotion Screen related
    SHOW_PROMOTION_SCREEN_LOADING: 'SHOW_PROMOTION_SCREEN_LOADING',
    HIDE_PROMOTION_SCREEN_LOADING: 'HIDE_PROMOTION_SCREEN_LOADING',
    UPDATE_PROMOTION_DETAILS: 'UPDATE_PROMOTION_DETAILS',
    APPLY_PROMOCODE_SUCCESS: 'APPLY_PROMOCODE_SUCCESS',
    APPLY_PROMOCODE_FAILED: 'APPLY_PROMOCODE_FAILED',
    REMOVE_PROMOCODE: 'REMOVE_PROMOCODE',
    SHOW_REDEEM_NOW_TEXT: 'SHOW_REDEEM_NOW_TEXT',
    GET_SAMPLE_AND_DISCOUNT_CHARGE: 'GET_SAMPLE_AND_DISCOUNT_CHARGE',
    SAMPLE_COLLECTED_AMOUNT_ADDED_IN_ARRAY:
      'SAMPLE_COLLECTED_AMOUNT_ADDED_IN_ARRAY',
    SAMPLE_COLLECTED_AMOUNT_ADDED_IN_TOTAL_AMOUNT:
      'SAMPLE_COLLECTED_AMOUNT_ADDED_IN_TOTAL_AMOUNT',

    // Lab Test related
    SHOW_TEST_SEARCH_LOADING: 'SHOW_TEST_SEARCH_LOADING',
    HIDE_TEST_SEARCH_LOADING: 'HIDE_TEST_SEARCH_LOADING',
    LAB_TEST_SEARCH_SUCCESS: 'LAB_TEST_SEARCH_SUCCESS',
    SET_CART_COUNT: 'SET_CART_COUNT',
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    SET_TOTAL_CART_AMOUNT: 'SET_TOTAL_CART_AMOUNT',
    LAB_TEST_SEARCH_TO_INITIAL: 'LAB_TEST_SEARCH_TO_INITIAL',
    CLEAR_LAB_TEST_SEARCH: 'CLEAR_LAB_TEST_SEARCH',

    //LabTestSummary
    SUMMARY_CART_COUNT: 'SUMMARY_CART_COUNT',
    SUMMARY_CART_AMOUNT: 'SUMMARY_CART_AMOUNT',
    SUMMARY_CART_ARRAY: 'SUMMARY_CART_ARRAY',
    SUMMARY_CART_BOOKING_DATE: 'SUMMARY_CART_BOOKING_DATE',
    SUMMARY_CART_BOOKING_TIME: 'SUMMARY_CART_BOOKING_TIME',
    SUMMARY_CART_BOOKING_TYPE: 'SUMMARY_CART_BOOKING_TYPE',
    BOOKING_HOME_WALKIN: 'BOOKING_HOME_WALKIN',
    BOOKING_DAYWISE_TIMESLOT: 'BOOKING_DAYWISE_TIMESLOT',

    // Profile Screeen related
    PROFILE_SHOW_LOADING: 'PROFILE_SHOW_LOADING',
    PROFILE_HIDE_LOADING: 'PROFILE_HIDE_LOADING',
    GET_PROFILE_DETAILS: 'GET_PROFILE_DETAILS',
    USER_PROFILE_IMAGE: 'USER_PROFILE_IMAGE',

    // Add Patient Info
    UPDATE_GENDER_LIST: 'UPDATE_GENDER_LIST',
    UPDATE_RELATION_LIST: 'UPDATE_RELATION_LIST',
    SHOW_SUBMIT_PATIENT_LOADING: 'SHOW_SUBMIT_PATIENT_LOADING',
    HIDE_SUBMIT_PATIENT_LOADING: 'HIDE_SUBMIT_PATIENT_LOADING',
    UPDATE_TITLE_LIST: 'UPDATE_TITLE_LIST',
    GET_LINKED_PATIENT_LIST: 'GET_LINKED_PATIENT_LIST',
    SHOW_SUBMIT_PATIENT_LIST_LOADING: 'SHOW_SUBMIT_PATIENT_LIST_LOADING',
    HIDE_SUBMIT_PATIENT_LIST_LOADING: 'HIDE_SUBMIT_PATIENT_LIST_LOADING',

    SHOW_DELETEPRESCRIPTION_LOADING: 'SHOW_DELETEPRESCRIPTION_SCREEN_LOADING',
    HIDE_DELETEPRESCRIPTION_LOADING: 'HIDE_DELETEPRESCRIPTION_SCREEN_LOADING',

    // Booking Rating and comments
    SHOW_BOOKINGCOMMENTS_LOADING: 'SHOW_BOOKINGCOMMENTS_SCREEN_LOADING',
    HIDE_BOOKINGCOMMENTS_LOADING: 'HIDE_BOOKINGCOMMENTS_SCREEN_LOADING',

    //Upload Prescription Screen
    SHOW_UPLOADPRESCRIPTION_LOADING: 'SHOW_UPLOADPRESCRIPTION_SCREEN_LOADING',
    HIDE_UPLOADPRESCRIPTION_LOADING: 'HIDE_UPLOADPRESCRIPTION_SCREEN_LOADING',
    UPLOADPRESCRIPTION_SUCCESS: 'UPLOADPRESCRIPTION_SUCCESS',
    SAVE_BASE64_FORMAT: 'SAVE_BASE64_FORMAT',
    DELETE_UPLOAD_IMAGE: 'DELETE_UPLOAD_IMAGE',
    SAVE_URI_FORMAT: 'SAVE_URI_FORMAT',

    //Add Patient Address
    SUBMIT_BUTTON_CLICKED: 'SUBMIT_BUTTON_CLICKED',
    SUBMIT_BUTTON_SUCCESS: 'SUBMIT_BUTTON_SUCCESS',
    SUBMIT_BUTTON_FAILED: 'SUBMIT_BUTTON_FAILED',
    EDIT_PATIENT_SHOW_LOADING: 'EDIT_PATIENT_SHOW_LOADING',
    EDIT_PATIENT_HIDE_LOADING: 'EDIT_PATIENT_HIDE_LOADING',
    UPDATE_ADDRESS_TYPE_LIST: 'UPDATE_ADDRESS_TYPE_LIST',

    //Update Patient Address
    UPDATE_BUTTON_CLICKED: 'UPDATE_BUTTON_CLICKED',
    UPDATE_BUTTON_SUCCESS: 'UPDATE_BUTTON_SUCCESS',
    UPDATE_BUTTON_FAILED: 'UPDATE_BUTTON_FAILED',

    //Notification
    NOTIFICATION_SHOW_LOADING: 'NOTIFICATION_SHOW_LOADING',
    NOTIFICATION_HIDE_LOADING: 'NOTIFICATION_HIDE_LOADING',
    GET_NOTIFICATION_DETAILS: 'GET_NOTIFICATION_DETAILS',
    SET_NOTIFICATION_COUNT: 'SET_NOTIFICATION_COUNT',
    SHOW_NOTIFICATION_LOADING: 'SHOW_NOTIFICATION_LOADING',
    HIDE_NOTIFICATION_LOADING: 'HIDE_NOTIFICATION_LOADING',
    NOTIFICATION_LIST_DATA: 'NOTIFICATION_LIST_DATA',
    SHOW_NOTIFICATION_UPDATE_LOADING: 'SHOW_NOTIFICATION_UPDATE_LOADING',
    HIDE_NOTIFICATION_UPDATE_LOADING: 'HIDE_NOTIFICATION_UPDATE_LOADING',
    UPDATE_NOTIFICATIONS: 'UPDATE_NOTIFICATIONS',

    //Sos
    SOS_SHOW_LOADING: 'SOS_SHOW_LOADING',
    SOS_HIDE_LOADING: 'SOS_HIDE_LOADING',
    GET_SOS_DETAILS: 'GET_SOS_DETAILS',

    // Tips Screen related
    SHOW_TIPS_SCREEN_LOADING: 'SHOW_TIPS_SCREEN_LOADING',
    HIDE_TIPS_SCREEN_LOADING: 'HIDE_TIPS_SCREEN_LOADING',
    GET_TIPS_DETAILS: 'GET_TIPS_DETAILS',

    //User List
    SHOW_USER_LIST_LOADING: 'SHOW_USER_LIST_LOADING',
    HIDE_USER_LIST_LOADING: 'HIDE_USER_LIST_LOADING',
    GET_USER_LIST_DETAILS: 'GET_USER_LIST_DETAILS',

    //Manage Address
    SHOW_MANAGEADDRESS_LOADING: 'SHOW_MANAGEADDRESS_SCREEN_LOADING',
    HIDE_MANAGEADDRESS_LOADING: 'HIDE_MANAGEADDRESS_SCREEN_LOADING',
    GET_MANAGEADDRESS_LIST_DETAILS: 'GET_MANAGEADDRESS_LIST_DETAILS',

    //Patient Info Screen
    SHOW_PATIENT_INFO_LOADING: 'SHOW_PATIENT_INFO_LOADING',
    HIDE_PATIENT_INFO_LOADING: 'HIDE_PATIENT_INFO_LOADING',
    SHOW_USER_ADDRESS_LOADING: 'SHOW_USER_ADDRESS_LOADING',
    HIDE_USER_ADDRESS_LOADING: 'HIDE_USER_ADDRESS_LOADING',
    UPDATE_PATIENT_INFO_LIST: 'UPDATE_PATIENT_INFO_LIST',
    UPDATE_USER_ADDRESS_LIST: 'UPDATE_USER_ADDRESS_LIST',
    SELECTED_ADDRESS: 'SELECTED_ADDRESS',
    SELECTED_PATIENT: 'SELECTED_PATIENT',
    PATIENT_INFO_NO_ADDRESS: 'PATIENT_INFO_NO_ADDRESS',
    PATIENT_INFO_NO_PATIENTS: 'PATIENT_INFO_NO_PATIENTS',
    LOGGINED_USER_MOBILE_NO: 'LOGGINED_USER_MOBILE_NO',
    LOGGINED_USER_FIRM_NO: 'LOGGINED_USER_FIRM_NO',
    PAYMENT_SET_CART_ARRAY: 'PAYMENT_SET_CART_ARRAY',
    PAYMENT_ORDER_BOOKING_SUCCESS_DATA: 'PAYMENT_ORDER_BOOKING_SUCCESS_DATA',

    //Test Trends
    SHOW_TESTTRENDS_LOADING: 'SHOW_TESTTRENDS_SCREEN_LOADING',
    HIDE_TESTTRENDS_LOADING: 'HIDE_TESTTRENDS_SCREEN_LOADING',
    GET_PATIENTLIST_DETAILS: 'GET_PATIENTLIST_DETAILS',
    GET_RESULT_DETAILS: 'GET_RESULT_DETAILS',
    GET_TESTLIST_DETAILS: 'GET_TESTLIST_DETAILS',

    //About Screen
    SHOW_ABOUTSCREEN_LOADING: 'SHOW_ABOUTSCREEN_LOADING',
    HIDE_ABOUTSCREEN_LOADING: 'HIDE_ABOUTSCREEN_LOADING',
    GET_ABOUTSCREEN_INFO: 'GET_ABOUTSCREEN_INFO',

    //Terms And Condition Screen
    SHOW_TERMS_SCREEN_LOADING: 'SHOW_TERMS_SCREEN_LOADING',
    HIDE_TERMS_SCREEN_LOADING: 'HIDE_TERMS_SCREEN_LOADING',
    GET_TERMS_SCREEN_INFO: 'GET_TERMS_SCREEN_INFO',

    //Contact Screen
    SHOW_CONTACT_SCREEN_LOADING: 'SHOW_CONTACT_SCREEN_LOADING',
    HIDE_CONTACT_SCREEN_LOADING: 'HIDE_CONTACT_SCREEN_LOADING',
    GET_CONTACT_SCREEN_INFO: 'GET_CONTACT_SCREEN_INFO',
    GET_CONTACT_MOBILE_NO: 'GET_CONTACT_MOBILE_NO',

    //Cash Payment
    SHOW_CASHPAYMENT_LOADING: 'SHOW_CASHPAYMENT_LOADING',
    HIDE_CASHPAYMENT_LOADING: 'HIDE_CASHPAYMENT_LOADING',
    GET_CASHPAYMENT_DETAILS: 'GET_CASHPAYMENT_DETAILS',
    //Online Payment
    SHOW_ONLINEPAYMENT_LOADING: 'SHOW_ONLINEPAYMENT_LOADING',
    HIDE_ONLINEPAYMENT_LOADING: 'HIDE_ONLINEPAYMENT_LOADING',
    GET_ONLINEPAYMENT_DETAILS: 'GET_ONLINEPAYMENT_DETAILS',
    GET_PAYUMONEY_DETAILS: 'GET_PAYUMONEY_DETAILS',


    //Calender Loading
    SHOW_CALENDER_LOADING: 'SHOW_CALENDER_LOADING',
    HIDE_CALENDER_LOADING: 'HIDE_CALENDER_LOADING',

    //Manage Branch
    SHOW_MANAGE_BRANCH_LOADING: 'SHOW_MANAGE_BRANCH_LOADING',
    HIDE_MANAGE_BRANCH_LOADING: 'HIDE_MANAGE_BRANCH_LOADING',
    UPDATE_MANAGE_BRANCH_LIST: 'UPDATE_MANAGE_BRANCH_LIST',
    UPDATE_DEFAULT_BRANCH: 'UPDATE_DEFAULT_BRANCH',

    //LabTestPaymentDetailsReducer
    PAYMENT_DETAIL_SHOW_LOADING: 'PAYMENT_DETAIL_SHOW_LOADING',
    PAYMENT_DETAIL_HIDE_LOADING: 'PAYMENT_DETAIL_HIDE_LOADING',

    //Config Action
    CONFIG_SET_CURRENCY: 'CONFIG_SET_CURRENCY',
    CONFIG_SET_FIRM_NAME: 'CONFIG_SET_FIRM_NAME',
    CONFIG_SET_FIRM_NO: 'CONFIG_SET_FIRM_NO',
    CONFIG_SET_UPLOAD_SIZE: 'CONFIG_SET_UPLOAD_SIZE',
    CONFIG_SET_PROFILE_UPLOAD_SIZE: 'CONFIG_SET_PROFILE_UPLOAD_SIZE',
    CONFIG_SET_MOBILE_NO: 'CONFIG_SET_MOBILE_NO',
    CONFIG_SHOW_LOADING: 'CONFIG_SHOW_LOADING',
    CONFIG_HIDE_LOADING: 'CONFIG_HIDE_LOADING',
    CONFIG_SET_DEVICE_INFO_DATA: 'CONFIG_SET_DEVICE_INFO_DATA',
    CONFIG_SET_ONLINE_PAYMENT_URL: 'CONFIG_SET_ONLINE_PAYMENT_URL',
    CONFIG_SET_DELIVERY_DISTANCE: 'CONFIG_SET_DELIVERY_DISTANCE',
    CONFIG_SET_BRANCH_LATITUDE: 'CONFIG_SET_BRANCH_LATITUDE',
    CONFIG_SET_BRANCH_LONGITUDE: 'CONFIG_SET_BRANCH_LONGITUDE',
    CONFIG_SET_PATIENT_LIMIT: 'CONFIG_SET_PATIENT_LIMIT',
    CONFIG_SHOW_MANAGE_ADDRESS: 'CONFIG_SHOW_MANAGE_ADDRESS',
    CONFIG_SET_MENU_LIST: 'CONFIG_SET_MENU_LIST',
    CONFIG_SHOW_SOS_ALERT: 'CONFIG_SHOW_SOS_ALERT',
    CONFIG_SHOW_IN_APP_NOTIFICATION: 'CONFIG_SHOW_IN_APP_NOTIFICATION',

    //LOGOUT
    LOGOUT_USER: 'LOGOUT_USER',

    //booking details
    BOOKING_DETAIL_SHOW_LOADING: 'BOOKING_DETAIL_SHOW_LOADING',
    BOOKING_DETAIL_HIDE_LOADING: 'BOOKING_DETAIL_HIDE_LOADING',
    BOOKING_DETAIL_DATA: 'BOOKING_DETAIL_DATA',
    SHOW_BOOKING_SERVICE_RATINGS_LOADING:
      'SHOW_BOOKING_SERVICE_RATINGS_LOADING',
    HIDE_BOOKING_SERVICE_RATINGS_LOADING:
      'HIDE_BOOKING_SERVICE_RATINGS_LOADING',
    SHOW_BOOKING_RATINGS_LOADING: 'SHOW_BOOKING_RATINGS_LOADING',
    HIDE_BOOKING_RATINGS_LOADING: 'HIDE_BOOKING_RATINGS_LOADING',
    SHOW_BOOKING_POST_REVIEW_LOADING: 'SHOW_BOOKING_POST_REVIEW_LOADING',
    HIDE_BOOKING_POST_REVIEW_LOADING: 'HIDE_BOOKING_POST_REVIEW_LOADING',
    BOOKING_DETAIL_DOWNLOAD_REPORT: 'BOOKING_DETAIL_DOWNLOAD_REPORT',
    SHOW_LOADING_DOWNLOAD_REPORT: 'SHOW_LOADING_DOWNLOAD_REPORT',
    HIDE_LOADING_DOWNLOAD_REPORT: 'HIDE_LOADING_DOWNLOAD_REPORT',
    SHOW_LOADING_DOWNLOAD_INVOICE: 'SHOW_LOADING_DOWNLOAD_INVOICE',
    HIDE_LOADING_DOWNLOAD_INVOICE: 'HIDE_LOADING_DOWNLOAD_INVOICE',
    BOOKING_DETAIL_DOWNLOAD_INVOICE: 'BOOKING_DETAIL_DOWNLOAD_INVOICE',
  },

  KEY: {
    ONE_SIGNAL_ID: 'ONE_SIGNAL_ID',
  },

  SCREEN_TITLE: {
    SCHEDULE: 'Schedule',
  },

  COLOR: {
    THEME_COLOR: '#F9A929',
    THEME_COLOR_2: '#F6461A',
    FONT_COLOR: '#3F3F3F',
    FONT_HINT: '#A19B9B',
    SCREEN_BG: '#F2F2F2',
    BUTTON_BG: '#1E75C0',
    WHITE_COLOR: '#FFFFFF',
    HALF_WHITE: '#fbfbfb',
    BLACK_COLOR: '#000000',

    BACKGROUND_COLOR_SCREEN: '#FAFBFB',
    FONT_COLOR_DEFAULT: '#797979',
    FONT_LINK_COLOR: '#80C0FE',

    // lab
    LAB_POPULAR_PRIZE: '#154e82',
    LAB_POPULAR_DISCOUNT: '#fd545c',
    LAB_POPULAR_BG: '#efefef',
    LAB_POPULAR_TOP: '#f35c24',
    UPLOAD_FILES_BG: '#DAE5F8',
    // lab

    //lab summary
    LAB_SUB_TOTAL_FONT: '#3A5BA1',
    LAB_CART_VIEW: '#f7f7f7',
    LAB_TOTAL_VIEW: '#f2f2f2',
    LAB_CART_ITEM_FONT: '#6C6C6C',
    LAB_HEADER_VIEW: '#F3F3F3',
    //lab summary

    //lab search
    LAB_SEARCH_SCREEN_BG: '#eef3fd',
    SEARCH_BG: '#eff4fd',
    LAB_SEARCH_TEXT: '#686868',
    LAB_SEARCH_BUTTON_BG: '#58afff',
    //lab search

    //lab payment
    LAB_PAYMENT_SCREEN_BG: '#fbfbfb',
    LAB_CHOOSE_BG: '#58afff',
    LAB_PAY_SUMMARY_BG: '#f7f7f7',
    LAB_PAY_TOTAL_BG: '#f2f2f2',
    LAB_PRICE_BG: '#329f2f',
    LAB_SUMMARY_TEXT: '#676767',
    LAB_PAY_BORDER: '#cdcdcd',
    LAB_PAY_SUB_HEADER_TEXT: '#9d9d9d',
    LAB_TOTAL_PRICE_BG: '#b82727',
    //lab payment

    //Bookings Row
    BOOK_LEFT_SIDE_BG: '#3C3636',
    BOOK_DATE_TIME_TEXT_COLOR: '#FFFAFA',
    BOOK_ADDRESS_TEXT_COLOR: '#282828',
    BOOK_ID_TEXT_COLOR: '#808080',
    BOOK_SUBMITTED_BG: '#67CD83',
    BOOK_PENDING_BG: '#F8C55C',
    BOOK_SHADOW_BG: '#676767',
    BOOK_PAY_BG: '#0F73CA',
    BOOK_PHONE_BG: '#BBBBBB',
    PAYMENT_STATUS_ONLINE: '#5AA218',
    CASH_ON_HAND: '#F2B94B',
    //Bookings Row

    //Order Success Screen
    ADDRESS_BACKGROUND: '#f7f7f7',
    //Order Success Screen

    //Settings
    SELECT_LOCATION_BG_COLOR: '#7E72FF',
    CUSTOMER_CALL_BG_COLOR: '#3E3E3F',
    CALL_US_BG_COLOR: '#080913',
  },

  FONT_SIZE: {
    BIG: 30,
    XXXL: 26,
    XXL: 23,
    XL: 20,
    L: 18,
    M: 16,
    SM: 14,
    S: 12,
    XS: 10,
    XXS: 8,
  },

  ALERT: {
    TITLE: {
      APP_NAME: 'Samiyak Health',
      INFO: 'Info',
      ERROR: 'Error',
      FAILED: 'Failed',
      SUCCESS: 'Success',
      UPDATE_SUCCESS: 'Updated Successfully',
      AUTH_FAILED: 'Authentication Failure',
      WENT_WRONG: 'Sorry, something went wrong',
      EXPIRED: 'Logout',
    },
    BTN: {
      OK: 'Ok',
      CANCEL: 'Cancel',
      YES: 'Yes',
      NO: 'No',
    },
    MESSAGE: {
      LOGOUT_MESSAGE: 'Do you want to logout?',
      DELETE_MESSAGE: 'Are you sure you want to Delete this Info?',
      CANCEL_ONLINE_PAYMENT: 'Are you sure want to cancel this transaction ?',
      ENABLE_LOCATION:
        'To continue,turn on device location,Which uses location service to open Settings',
      SELECT_LOCATION: 'Kindly select location from map',
      UPDATE_ADDRESS_SUCCESS: 'Address updated successfully',
      ADD_ADDRESS_SUCCESS: 'Address added successfully',
      CLEAR_ALL: 'Are you sure that you want to clear all notification?',
      MARK_ALL: 'Are you sure that you want to mark all notification as read?',
      ENABLE_LOCATION_PERMISSION:
        'Location permission denied - Enable it in settings',
      DOWNLOAD_MESSAGE: 'Are you sure you want to download this file?',
    },
  },

  VALIDATION_MSG: {
    LOGIN_VALIDATION: 'Please enter valid username and password',
    ERROR_CATCH: 'Request Failed',
    NO_INTERNET: 'Please check your internet connectivity.',
    WENT_WRONG: "We're working on it and we'll get it fixed as soon as we can.",
    NO_NAME: 'Name is required',
    NO_TITLE: 'Patient title is required',
    NO_EMAIL: 'Email is required',
    NO_FIRSTNAME: 'First Name is required',
    NO_LASTNAME: 'Last Name is required',
    NO_USERNAME: 'Valid User Name is required',
    NO_EMP_ID: 'Empolyee ID is required',
    NO_PASSWORD: 'Need atleast 8 characters in password',
    MATCH_PASSWORD: 'Password did not match',
    VALID_PASSWORD:
      'The Password should be 8 or more characters Alpha Numeric value',
    NO_DOB: 'Date of Birth is required',
    NO_MOBILE_NO: 'Valid Phone Number is required',
    INVALID_EMAIL: 'Invalid Email Address',
    CHECK_USERNAME_FAILED: 'Unable to check username try again later',
    SIGNUP_FAILED:
      'Signup failed. Please check the provided inputs and try again',
    ALREADY_SIGNUP:
      'Already signedup. Please login using your mobile number and password',
    NOT_FOUND_SIGNUP:
      'Unable to signup. Please check the provided inputs and try again',
    NEED_DOB_SIGNUP:
      'Found a difficulty on registration. Please enter Date of Birth',
    DUPLICATE_SIGNUP:
      'Found a difficulty on registration. Please contact the support team',
    SETPASSWORD_FAILED: 'Failed to save password',

    NO_OTP: 'Valid OTP is required',
    OTP_RESEND_SUCCESS: 'New OTP sent to the registered mobile number',
    OTP_RESEND_FAILED: 'Unable to send OTP now. Please try after sometime',
    OTP_VERIFY_FAILED: 'OTP verification failed. Please try again later',
    OTP_VERIFY_CHECK: 'Kindly verify the OTP',

    AUTH_FAILED: 'The username and password you entered does not match',
    REQ_FAILED: 'Request failed',
    NO_DATA_FOUND: 'No data found',
    NO_GENDER: 'Gender is required',
    NO_RELATION: 'Relation is required',
    NO_ADDRESS1: 'Address Line 1 is required',
    NO_ADDRESS2: 'Address Line 2 is required',
    NO_CITY: 'City is required',
    NO_STATE: 'State is required',
    NO_PINCODE: 'Pincode is required',
    NO_STREET: 'Street is required',
    NO_PLACE: 'Place is required',
    INPUT_VALIDATION_ERROR: 'Invalid username or password',
    NO_PREFERED_LOCATION: 'Preferred location is required',
    NO_ADDRESS_TYPE: 'Address type is required',
    NO_PROMOTION: 'No PromoCode found',
    NO_ADDRESS: 'No Address Found.Kindly add your address',
    ADDRESS_ALERT: 'Cannot able to get the address',
    CHECK_TERMS_CONDITION: 'Kindly select Terms and Condition',
    NO_TEST_SELECTED: 'Kindly choose test or upload prescription to proceed',
    NO_DATE_TIME_SELECTED: 'Kindly select Date and Time',
    NO_PATIENT_SELECTED: 'Kindly select the patient to proceed',
    NO_PATIENT_ADDRESS_SELECTED:
      'Kindly select the patient and Address to proceed',
    NO_BRANCH: 'Kindly select your branch',
    BRANCH_UPDATED: 'Branch updated Successfully',
    UPLOAD_FILE_SIZE: 'File Size too large. Kindly pick another one',
    UPLOAD_FORMAT: 'Supports only images/pdf files',
    BOOKING_TIME_SLOT_ERROR:
      'Time slot not available for the selected date. Kindly select different Date',
    PROFILE_UPDATE_SUCCESS: 'Profile updated successfully',
    DISTANCE_LONG: 'Our service is currently not available for this location',
    NO_LAT_LNG: 'Kindly Choose your location in Map',
    UPDATE_ADDRESS_ON_MAP: 'Kindly Update your address on Map',
    //Notification
    SET_NOTIFICATION_COUNT: 'SET_NOTIFICATION_COUNT',
    SHOW_NOTIFICATION_LOADING: 'SHOW_NOTIFICATION_LOADING',
    HIDE_NOTIFICATION_LOADING: 'HIDE_NOTIFICATION_LOADING',
    NO_PATIENT_LINK: 'No patient available to link. Kindly add new patient',
    NO_PATIENT: 'No patient selected',
  },

  HTTP_CODE: {
    SUCCESS: 200,
    INSERT_SUCESS: 201,
    AUTHENTICATION_FAILURE: 401,
    REQUIRED_MISSING: 403,
    REQUEST_TIMED_OUT_FAILURE: 500,
    INPUT_VALIDATION_ERROR: 400,
    NO_DATA_FOUND: 404,
    NO_INTERNET: 503,
    UNPROCESSABLE_ENTITY: 422,
  },

  ASYNC: {
    ASYNC_PHONE_NUMBER: '@phoneNumber',
    ASYNC_OTP: '@otp',
    ASYNC_PASSWORD: '@password',
    ASYNC_LOGIN_SUCCESS: '@login_success',
    ASYNC_DEFAULT_BRANCH_NAME: '@default_branch_name',
    ASYNC_DEFAULT_FIRM_NO: '@default_firm_no',
    ASYNC_USER_IMAGE_URL: '@user_image_uRL',
    ASYNC_BRANCH_LATITUDE: '@user_branch_latitude',
    ASYNC_BRANCH_LONGITUDE: '@user_branch_longitude',
  },
};
